DROP TABLE IF EXISTS urls;

CREATE TABLE URLS (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    protocol VARCHAR(255) NOT NULL,
    authority VARCHAR(255) NOT NULL,
    created_at TIMESTAMP
);
